# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-22 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('quote', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('favorites', models.ManyToManyField(related_name='usersThatFavorite', to='beltApp.User')),
                ('submitted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userThatSubmitted', to='beltApp.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='submitted',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
